"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import styles from "./page.module.css";
import { AuthGate } from "./auth-gate";
import { createClient } from "@/lib/supabase/client";

type Ownership = "Person 1" | "Person 2" | "Joint";
type Property = { id: string | number; name: string; address: string; ownership: Ownership; p1: number; p2: number; active: boolean };
type Entry = { id: string | number; kind: "Rent" | "Expense" | "Interest" | "Pension" | "Other"; date: string; description: string; amount: number; ownership: Ownership; property?: string; category?: string; receipt?: boolean; review?: boolean };
type TaxYear = { id: string; label: string; starts_on: string; ends_on: string };
type StoredDocument = { id: string; transaction_id: string | null; tax_year_id: string | null; original_name: string; mime_type: string | null; storage_path: string; url?: string };
type RecordArea = { id: string; name: string; record_scope: "household" | "personal" };

const money = (amount: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" }).format(amount);
const currentYear = "2025–26 (6 April 2025 – 5 April 2026)";
const taxOnBands = (taxable: number) => Math.min(taxable, 37700) * .2 + Math.min(Math.max(0, taxable - 37700), 74870) * .4 + Math.max(0, taxable - 112570) * .45;
const estimateIncomeTax = (nonSavingsIncome: number, savingsInterest: number) => { const totalIncome = nonSavingsIncome + savingsInterest; const allowance = Math.max(0, 12570 - Math.max(0, totalIncome - 100000) / 2); const taxableNonSavings = Math.max(0, nonSavingsIncome - allowance); const remainingAllowance = Math.max(0, allowance - nonSavingsIncome); const savingsAllowance = totalIncome <= 50270 ? 1000 : totalIncome <= 125140 ? 500 : 0; const taxableSavings = Math.max(0, savingsInterest - remainingAllowance - savingsAllowance); return taxOnBands(taxableNonSavings) + taxOnBands(taxableNonSavings + taxableSavings) - taxOnBands(taxableNonSavings); };

function TaxApp() {
  const [tab, setTab] = useState("Dashboard");
  const [year, setYear] = useState(currentYear);
  const [properties, setProperties] = useState<Property[]>([]);
  const [entries, setEntries] = useState<Entry[]>([]);
  const [documents, setDocuments] = useState<StoredDocument[]>([]);
  const [householdId, setHouseholdId] = useState<string | null>(null);
  const [recordAreas, setRecordAreas] = useState<RecordArea[]>([]);
  const [taxYearId, setTaxYearId] = useState<string | null>(null);
  const [taxYears, setTaxYears] = useState<TaxYear[]>([]);
  const [p1Name, setP1Name] = useState("Person 1");
  const [p2Name, setP2Name] = useState("Person 2");
  const [notice, setNotice] = useState("");
  const [showForm, setShowForm] = useState<"property" | "entry" | null>(null);
  const [editingProperty, setEditingProperty] = useState<Property | null>(null);
  const [entryKind, setEntryKind] = useState<Entry["kind"]>("Rent");
  const totals = useMemo(() => {
    const rented = entries.filter(e => e.kind === "Rent").reduce((a, e) => a + e.amount, 0);
    const expenses = entries.filter(e => e.kind === "Expense").reduce((a, e) => a + e.amount, 0);
    const interest = entries.filter(e => e.kind === "Interest").reduce((a, e) => a + e.amount, 0);
    const pension = entries.filter(e => e.kind === "Pension").reduce((a, e) => a + e.amount, 0);
    const p1 = entries.reduce((a, e) => a + e.amount * (e.ownership === "Person 1" ? 1 : e.ownership === "Joint" ? .5 : 0), 0);
    const p2 = entries.reduce((a, e) => a + e.amount * (e.ownership === "Person 2" ? 1 : e.ownership === "Joint" ? .5 : 0), 0);
    return { rented, expenses, interest, pension, p1, p2 };
  }, [entries]);
  useEffect(() => {
    const load = async () => {
      const supabase = createClient(); const { data: userData } = await supabase.auth.getUser();
      if (!userData.user) return;
      const { data: memberships, error: membershipError } = await supabase.from("household_members").select("household_id").eq("user_id", userData.user.id);
      if (membershipError || !memberships?.length) { setNotice(`Could not open your records: ${membershipError?.message ?? "no record access found"}`); return; }
      const memberIds = memberships.map(member => member.household_id);
      const { data: areas, error: areaError } = await supabase.from("households").select("id, name, record_scope").in("id", memberIds);
      if (areaError || !areas?.length) { setNotice(`Could not open your record areas: ${areaError?.message ?? "none found"}`); return; }
      const availableAreas = areas as RecordArea[];
      setRecordAreas(availableAreas);
      const storedAreaId = window.localStorage.getItem("bradley-tax-record-area");
      const activeAreaId = householdId && memberIds.includes(householdId) ? householdId : availableAreas.find(area => area.id === storedAreaId)?.id ?? availableAreas[0].id;
      if (activeAreaId !== householdId) { setHouseholdId(activeAreaId); return; }
      const [{ data: dbProperties }, { data: years }, { data: taxpayers }] = await Promise.all([supabase.from("properties").select("*").eq("household_id", activeAreaId), supabase.from("tax_years").select("*").eq("household_id", activeAreaId).order("starts_on"), supabase.from("taxpayers").select("label, display_name").eq("household_id", activeAreaId)]);
      setP1Name(taxpayers?.find((person: any) => person.label === "person_1")?.display_name ?? "Person 1");
      setP2Name(taxpayers?.find((person: any) => person.label === "person_2")?.display_name ?? "Person 2");
      const loadedYears = (years ?? []) as TaxYear[]; setTaxYears(loadedYears);
      const selectedYear = loadedYears.find((item: any) => item.label === "2025-26") ?? loadedYears[0]; if (!selectedYear) return;
      setTaxYearId(selectedYear.id);
      setYear(`${selectedYear.label.slice(0, 4)}–${selectedYear.label.slice(5)} (6 April ${selectedYear.starts_on.slice(0,4)} – 5 April ${selectedYear.ends_on.slice(0,4)})`);
      const propertyList: Property[] = ((dbProperties ?? []) as any[]).map(p => ({ id:p.id, name:p.name, address:p.address ?? "", ownership:(p.ownership === "person_1" ? "Person 1" : p.ownership === "person_2" ? "Person 2" : "Joint") as Ownership, p1:Number(p.person_1_pct), p2:Number(p.person_2_pct), active:p.active }));
      setProperties(propertyList);
      const [{ data: dbEntries }, { data: dbDocuments }] = await Promise.all([supabase.from("transactions").select("*").eq("tax_year_id", selectedYear.id).order("occurred_on", { ascending:false }), supabase.from("documents").select("*").eq("household_id", activeAreaId).eq("tax_year_id", selectedYear.id).order("created_at", { ascending:false })]);
      const kindMap: Record<string, Entry["kind"]> = { rental_income:"Rent", property_expense:"Expense", bank_interest:"Interest", private_pension:"Pension", state_pension:"Pension", other_income:"Other" };
      setEntries(((dbEntries ?? []) as any[]).map(e => ({ id:e.id, kind:kindMap[e.kind] ?? "Other", date:e.occurred_on, description:e.description ?? "", amount:Number(e.gross_amount), ownership:(e.ownership === "person_1" ? "Person 1" : e.ownership === "person_2" ? "Person 2" : "Joint") as Ownership, property:propertyList.find(p=>p.id===e.property_id)?.name, category:e.expense_category, review:e.needs_review })));
      const documentsWithUrls = await Promise.all(((dbDocuments ?? []) as any[]).map(async document => { const { data: signed } = await supabase.storage.from("tax-documents").createSignedUrl(document.storage_path, 3600); return { ...document, url:signed?.signedUrl } as StoredDocument; }));
      setDocuments(documentsWithUrls);
    }; load();
  }, [householdId]);
  const changeRecordArea = (id: string) => {
    window.localStorage.setItem("bradley-tax-record-area", id);
    setEntries([]); setDocuments([]); setProperties([]); setTaxYears([]); setTaxYearId(null);
    setHouseholdId(id);
  };
  const openEntry = (kind: Entry["kind"]) => { setEntryKind(kind); setShowForm("entry"); };
  const changeTaxYear = async (id: string) => { const selected = taxYears.find(item => item.id === id); if (!selected || !householdId) return; setTaxYearId(id); setYear(`${selected.label.slice(0, 4)}–${selected.label.slice(5)} (6 April ${selected.starts_on.slice(0,4)} – 5 April ${selected.ends_on.slice(0,4)})`); const supabase = createClient(); const [{ data }, { data: dbDocuments }] = await Promise.all([supabase.from("transactions").select("*").eq("tax_year_id", id).order("occurred_on", { ascending:false }), supabase.from("documents").select("*").eq("household_id", householdId).eq("tax_year_id", id).order("created_at", { ascending:false })]); const kindMap: Record<string, Entry["kind"]> = { rental_income:"Rent", property_expense:"Expense", bank_interest:"Interest", private_pension:"Pension", state_pension:"Pension", other_income:"Other" }; setEntries(((data ?? []) as any[]).map(e => ({ id:e.id, kind:kindMap[e.kind] ?? "Other", date:e.occurred_on, description:e.description ?? "", amount:Number(e.gross_amount), ownership:(e.ownership === "person_1" ? "Person 1" : e.ownership === "person_2" ? "Person 2" : "Joint") as Ownership, property:properties.find(p=>p.id===e.property_id)?.name, category:e.expense_category, review:e.needs_review }))); const documentsWithUrls = await Promise.all(((dbDocuments ?? []) as any[]).map(async document => { const { data: signed } = await supabase.storage.from("tax-documents").createSignedUrl(document.storage_path, 3600); return { ...document, url:signed?.signedUrl } as StoredDocument; })); setDocuments(documentsWithUrls); };
  const saveEntry = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    const receiptFile = data.get("receipt") as File | null;
    const hasReceipt = Boolean(receiptFile && receiptFile.size > 0);
    const item: Entry = { id: Date.now(), kind: entryKind, date: String(data.get("date")), description: String(data.get("description")), amount: Number(data.get("amount")), ownership: data.get("ownership") as Ownership, property: String(data.get("property") || ""), category: String(data.get("category") || ""), receipt: hasReceipt, review: Boolean(data.get("review")) };
    if (!householdId || !taxYearId) { setNotice("Your secure household is still loading. Please try again in a moment."); return; }
    const ownership = item.ownership === "Person 1" ? "person_1" : item.ownership === "Person 2" ? "person_2" : "joint";
    const property = properties.find(p => p.name === item.property);
    const kindMap: Record<Entry["kind"], string> = { Rent:"rental_income", Expense:"property_expense", Interest:"bank_interest", Pension:"private_pension", Other:"other_income" };
    const { data: savedTransaction, error } = await createClient().from("transactions").insert({ household_id:householdId, tax_year_id:taxYearId, property_id:property?.id as string | undefined, kind:kindMap[item.kind], occurred_on:item.date, description:item.description, gross_amount:item.amount, ownership, expense_category:item.category || null, needs_review:Boolean(item.review) }).select().single();
    if (error) { setNotice(`Could not save: ${error.message}`); return; }
    item.id = savedTransaction.id; setEntries([item, ...entries]); setShowForm(null);
    if (!hasReceipt || !receiptFile) { setNotice("Saved securely."); return; }
    const safeName = receiptFile.name.replace(/[^a-zA-Z0-9._-]/g, "_");
    const storagePath = `${householdId}/${taxYearId}/${crypto.randomUUID()}-${safeName}`;
    const supabase = createClient();
    const { error: uploadError } = await supabase.storage.from("tax-documents").upload(storagePath, receiptFile, { contentType: receiptFile.type || undefined, upsert:false });
    if (uploadError) { setNotice(`Record saved, but the receipt could not upload: ${uploadError.message}`); return; }
    const { data: savedDocument, error: documentError } = await supabase.from("documents").insert({ household_id:householdId, transaction_id:savedTransaction.id, property_id:property?.id ?? null, tax_year_id:taxYearId, storage_path:storagePath, original_name:receiptFile.name, mime_type:receiptFile.type || null, document_type:"receipt" }).select().single();
    if (documentError) { setNotice(`Record and file saved, but the receipt link could not be created: ${documentError.message}`); return; }
    const { data: signed } = await supabase.storage.from("tax-documents").createSignedUrl(storagePath, 3600);
    setDocuments(previous => [{ ...savedDocument, url:signed?.signedUrl } as StoredDocument, ...previous]);
    setNotice("Record and receipt saved securely.");
  };
  const saveProperty = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const d = new FormData(event.currentTarget); if (!householdId) { setNotice("Your secure household is still loading. Please try again in a moment."); return; } const item = { name: String(d.get("name")), address: String(d.get("address")), ownership: d.get("ownership") as Ownership, p1: Number(d.get("p1")), p2: Number(d.get("p2")), active: d.get("active") === "on" }; if (item.p1 + item.p2 !== 100) { setNotice("Ownership percentages must add up to 100%."); return; } const dbOwnership = item.ownership === "Person 1" ? "person_1" : item.ownership === "Person 2" ? "person_2" : "joint"; const values = { name:item.name, address:item.address, ownership:dbOwnership, person_1_pct:item.p1, person_2_pct:item.p2, active:item.active }; const query = editingProperty ? createClient().from("properties").update(values).eq("id", editingProperty.id).select().single() : createClient().from("properties").insert({ household_id:householdId, ...values }).select().single(); const { data, error } = await query; if(error){setNotice(`Could not save: ${error.message}`);return;} const saved = { ...item, id:data.id }; setProperties(editingProperty ? properties.map(property => property.id === editingProperty.id ? saved : property) : [...properties, saved]); setEditingProperty(null); setShowForm(null); setNotice(editingProperty ? "Property updated securely." : "Property saved securely."); };
  const editProperty = (property: Property) => { setEditingProperty(property); setShowForm("property"); };
  const deleteProperty = async (property: Property) => { const { count, error: checkError } = await createClient().from("transactions").select("id", { count:"exact", head:true }).eq("property_id", property.id); if (checkError) { setNotice(`Could not check property records: ${checkError.message}`); return; } if ((count ?? 0) > 0) { const { error } = await createClient().from("properties").update({ active:false }).eq("id", property.id); if (error) { setNotice(`Could not mark property inactive: ${error.message}`); return; } setProperties(properties.map(item => item.id === property.id ? { ...item, active:false } : item)); setNotice("This property has records, so it was marked inactive rather than deleted."); return; } if (!window.confirm(`Delete ${property.name}?`)) return; const { error } = await createClient().from("properties").delete().eq("id", property.id); if (error) { setNotice(`Could not delete property: ${error.message}`); return; } setProperties(properties.filter(item => item.id !== property.id)); setNotice("Property deleted."); };
  const addFamilyUser = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const email = String(new FormData(event.currentTarget).get("email")); const { data, error } = await createClient().functions.invoke("invite-household-member", { body: { email } }); setNotice(error ? error.message : data?.message ?? `An invitation has been sent to ${email}.`); };
  const saveNames = async () => { if (!householdId) { setNotice("Your secure household is still loading. Please try again in a moment."); return; } const { error } = await createClient().from("taxpayers").upsert([{ household_id: householdId, label: "person_1", display_name: p1Name.trim() || "Person 1", sort_order: 1 }, { household_id: householdId, label: "person_2", display_name: p2Name.trim() || "Person 2", sort_order: 2 }], { onConflict: "household_id,label" }); setNotice(error ? `Could not save: ${error.message}` : "Names saved securely."); };
  const addTaxYear = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!householdId) return; const data = new FormData(event.currentTarget); const start = String(data.get("start")); const end = String(data.get("end")); const label = `${start.slice(0,4)}-${end.slice(2,4)}`; const { data: saved, error } = await createClient().from("tax_years").insert({ household_id:householdId, label, starts_on:start, ends_on:end }).select().single(); if(error) { setNotice(`Could not add tax year: ${error.message}`); return; } setTaxYears([...taxYears, saved]); setNotice(`${label} tax year added.`); event.currentTarget.reset(); };
  const createPrivateRecordArea = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    const { data: createdId, error } = await createClient().rpc("create_private_tax_records", { record_name: String(data.get("recordName")), first_taxpayer_name: String(data.get("taxpayerName")) });
    if (error) { setNotice(`Could not create private records: ${error.message}`); return; }
    setNotice("Your private tax records have been created. Nobody else in the family can access them.");
    changeRecordArea(createdId as string);
  };
  const deleteEntry = async (id: string | number) => { if (!window.confirm("Delete this record? This cannot be undone.")) return; const { error } = await createClient().from("transactions").delete().eq("id", id); if (error) { setNotice(`Could not delete: ${error.message}`); return; } setEntries(entries.filter(entry => entry.id !== id)); setNotice("Record deleted."); };
  return <main className={styles.app}>
    <header className={styles.header}><div><p className={styles.eyebrow}>Private household tax record keeping</p><h1>Bradley Tax Records</h1></div><div className={styles.headerSelectors}><label className={styles.year}>Record area<select value={householdId ?? ""} onChange={e => changeRecordArea(e.target.value)}>{recordAreas.map(area => <option key={area.id} value={area.id}>{area.name}{area.record_scope === "personal" ? " (private)" : ""}</option>)}</select></label><label className={styles.year}>Tax year<select value={taxYearId ?? ""} onChange={e => changeTaxYear(e.target.value)}>{taxYears.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label></div></header>
    <nav className={styles.nav}>{["Dashboard", "Properties", "Income", "Expenses", "Receipts", "Tax Summary", "Documents", "Settings"].map(item => <button className={tab === item ? styles.active : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</nav>
    {notice && <div className={styles.notice}>{notice}<button onClick={() => setNotice("")}>Dismiss</button></div>}
    {tab === "Dashboard" && <>
      <section className={styles.hero}><div><p>{year}</p><h2>Everything ready for your tax return, in one place.</h2><span>Record figures as they happen. Check the final figures before you use them on HMRC Self Assessment.</span></div><button className={styles.primary} onClick={() => setTab("Tax Summary")}>View Tax Summary</button></section>
      <section className={styles.actions}><button onClick={() => openEntry("Rent")}>＋ Add Rental Income</button><button onClick={() => openEntry("Expense")}>＋ Add Property Expense</button><button onClick={() => openEntry("Pension")}>＋ Add Pension</button><button onClick={() => openEntry("Interest")}>＋ Add Bank Interest</button><button onClick={() => openEntry("Other")}>＋ Add Other Income</button><button onClick={() => openEntry("Expense")}>▣ Photograph / Upload Receipt</button></section>
      <section className={styles.cards}><Stat title={`${p1Name} total recorded`} value={money(totals.p1)} /><Stat title={`${p2Name} total recorded`} value={money(totals.p2)} /><Stat title="Joint income recorded" value={money(entries.filter(e => e.ownership === "Joint" && e.kind !== "Expense").reduce((a,e)=>a+e.amount,0))} /><Stat title="Total rental income" value={money(totals.rented)} /><Stat title="Property expenses" value={money(totals.expenses)} /><Stat title="Net property profit" value={money(totals.rented-totals.expenses)} /><Stat title="Private pension income" value={money(totals.pension)} /><Stat title="Bank interest" value={money(totals.interest)} /></section>
      <section className={styles.review}><h2>Things to check</h2><p>{entries.filter(e => e.kind === "Expense" && !e.receipt).length} expense(s) have no receipt. {entries.filter(e => e.review).length} item(s) need tax treatment checking.</p><button onClick={() => setTab("Expenses")}>Review records</button></section>
    </>}
    {tab === "Properties" && <section><div className={styles.sectionHead}><div><h2>Properties</h2><p>Keep each rental property here. Ownership automatically determines the allocation.</p></div><button className={styles.primary} onClick={() => { setEditingProperty(null); setShowForm("property"); }}>Add property</button></div><div className={styles.list}>{properties.map(p => <article className={styles.row} key={p.id}><div><strong>{p.name}</strong><span>{p.address}</span></div><div><b>{p.ownership}</b><span>{p.p1}% / {p.p2}%</span></div><span className={styles.pill}>{p.active ? "Active" : "Inactive"}</span><button onClick={() => editProperty(p)}>Edit</button><button onClick={() => deleteProperty(p)}>Delete</button></article>)}</div></section>}
    {(tab === "Income" || tab === "Expenses") && <Records entries={entries} tab={tab} openEntry={openEntry} onDelete={deleteEntry} />}
    {(tab === "Receipts" || tab === "Documents") && <DocumentsList documents={documents} />}
    {tab === "Tax Summary" && <><TaxSummary entries={entries} properties={properties} totals={totals} p1={p1Name} p2={p2Name} /><ReceiptAppendix documents={documents} /></>}
    {tab === "Settings" && <section className={styles.settings}><h2>Settings</h2><label>Person 1 name<input value={p1Name} onChange={event => setP1Name(event.target.value)} /></label><label>Person 2 name<input value={p2Name} onChange={event => setP2Name(event.target.value)} /></label><button className={styles.primary} onClick={saveNames}>Save names</button><h3>Add future tax year</h3><form onSubmit={addTaxYear}><label>Start date<input name="start" type="date" required /></label><label>End date<input name="end" type="date" required /></label><button className={styles.primary}>Add tax year</button></form><h3>Add an authorised family user</h3><p>Enter their email address and the app will send them a secure invitation to set their own password. Nobody can create an account from the public sign-in page.</p><form onSubmit={addFamilyUser}><label>Email address<input name="email" type="email" required /></label><button className={styles.primary}>Send invitation</button></form><h3>HMRC mapping – 2025–26</h3><p>These labels and box numbers are kept separate from your financial records. Check and update them when HMRC releases a new year’s return.</p><div className={styles.mapping}><span>SA105 box 20</span><b>Total rents and other income</b><span>SA105 box 24</span><b>Rent, rates, insurance and ground rents</b><span>SA105 box 25</span><b>Property repairs and maintenance</b></div></section>}
    {tab === "Settings" && !recordAreas.some(area => area.record_scope === "personal") && <section className={styles.settings}><h3>Create your own private tax records</h3><p>This creates a completely separate record area for you. Your parents will not be able to see or open it.</p><form onSubmit={createPrivateRecordArea}><label>Name for this record area<input name="recordName" defaultValue="My Tax Records" required /></label><label>Your name<input name="taxpayerName" defaultValue="Stephen Bradley" required /></label><button className={styles.primary}>Create my private records</button></form></section>}
    {showForm === "entry" && <EntryForm kind={entryKind} properties={properties} p1Name={p1Name} p2Name={p2Name} onSave={saveEntry} onCancel={() => setShowForm(null)} />}
    {showForm === "property" && <PropertyForm p1Name={p1Name} p2Name={p2Name} initial={editingProperty} onSave={saveProperty} onCancel={() => { setEditingProperty(null); setShowForm(null); }} />}
  </main>;
}
function Stat({title,value}:{title:string;value:string}) { return <article className={styles.stat}><span>{title}</span><strong>{value}</strong></article>; }
function Records({entries,tab,openEntry,onDelete}:{entries:Entry[];tab:string;openEntry:(x:Entry["kind"])=>void;onDelete:(id:string|number)=>void}) { const filtered=entries.filter(e=>tab==="Expenses"?e.kind==="Expense":tab==="Income"?e.kind!=="Expense":true); return <section><div className={styles.sectionHead}><div><h2>{tab}</h2><p>All figures shown are for the selected tax year.</p></div>{tab === "Expenses" && <button className={styles.primary} onClick={()=>openEntry("Expense")}>Add expense</button>}{tab === "Income" && <button className={styles.primary} onClick={()=>openEntry("Rent")}>Add income</button>}</div><div className={styles.list}>{filtered.map(e=><article className={styles.row} key={e.id}><div><strong>{e.description}</strong><span>{e.date} · {e.property || e.kind} · {e.ownership}</span></div><div><b>{money(e.amount)}</b><span>{e.category}</span></div><button onClick={()=>onDelete(e.id)}>Delete</button></article>)}{!filtered.length&&<p className={styles.empty}>Nothing recorded yet.</p>}</div></section> }
function DocumentsList({documents}:{documents:StoredDocument[]}) { return <section><div className={styles.sectionHead}><div><h2>Receipts & documents</h2><p>Files are stored privately and shown for the selected tax year.</p></div></div><div className={styles.list}>{documents.map(document => <article className={styles.row} key={document.id}><div><strong>{document.original_name}</strong><span>{document.mime_type?.startsWith("image/") ? "Image receipt" : "Document"}</span>{document.url && document.mime_type?.startsWith("image/") && <img src={document.url} alt={`Preview of ${document.original_name}`} style={{ display:"block", marginTop:10, maxWidth:220, maxHeight:180, objectFit:"contain", borderRadius:6 }} />}</div>{document.url ? <a href={document.url} target="_blank" rel="noreferrer">Open / download</a> : <span>Preview unavailable</span>}</article>)}{!documents.length&&<p className={styles.empty}>No receipts or documents have been uploaded for this tax year yet.</p>}</div></section> }
function ReceiptAppendix({documents}:{documents:StoredDocument[]}) { if (!documents.length) return null; return <section className={styles.summary}><h2>Receipts and documents</h2><p>Image receipts are included below when you print or save this report as a PDF.</p><div className={styles.list}>{documents.map(document => <article className={styles.row} key={document.id}><div><strong>{document.original_name}</strong>{document.url && document.mime_type?.startsWith("image/") ? <img src={document.url} alt={`Receipt: ${document.original_name}`} style={{ display:"block", marginTop:10, maxWidth:"100%", maxHeight:500, objectFit:"contain" }} /> : <span>Attached document (open it from the Documents tab).</span>}</div></article>)}</div></section> }
function TaxSummary({entries,properties,totals,p1,p2}:{entries:Entry[];properties:Property[];totals:{rented:number;expenses:number;interest:number;pension:number;p1:number;p2:number};p1:string;p2:string}) { return <section><div className={styles.sectionHead}><div><h2>Tax Summary</h2><p>Record-keeping aid only — review unusual tax treatment before entering figures into HMRC.</p></div><button className={styles.primary} onClick={()=>window.print()}>Print / save PDF</button></div>{[p1,p2].map((person,index)=>{const storedOwnership=index === 0 ? "Person 1" : "Person 2"; const share=(e:Entry)=>e.ownership===storedOwnership?1:e.ownership==="Joint"?.5:0;const rent=entries.filter(e=>e.kind==="Rent").reduce((a,e)=>a+e.amount*share(e),0);const exp=entries.filter(e=>e.kind==="Expense").reduce((a,e)=>a+e.amount*share(e),0);const interest=entries.filter(e=>e.kind==="Interest").reduce((a,e)=>a+e.amount*share(e),0);const pension=entries.filter(e=>e.kind==="Pension").reduce((a,e)=>a+e.amount*share(e),0);const other=entries.filter(e=>e.kind==="Other").reduce((a,e)=>a+e.amount*share(e),0);const rentCosts=entries.filter(e=>e.kind==="Expense"&&(e.category??"").includes("Rent")).reduce((a,e)=>a+e.amount*share(e),0);const nonSavingsIncome=Math.max(0,rent-exp)+pension+other;return <article className={styles.summary} key={person}><h2>{person}</h2><div className={styles.summaryGrid}><Stat title="Rental income" value={money(rent)}/><Stat title="Allowable expenses" value={money(exp)}/><Stat title="Property profit / loss" value={money(rent-exp)}/><Stat title="Bank interest" value={money(interest)}/><Stat title="Private pensions" value={money(pension)}/><Stat title="Estimated income tax owed" value={money(estimateIncomeTax(nonSavingsIncome, interest))}/></div><p><small>Estimate includes the standard England/Wales personal allowance and savings allowance (£1,000 basic rate, £500 higher rate, nil additional rate). It excludes tax already paid, the starting savings rate, dividends, capital gains, pension relief and other adjustments.</small></p><h3>HMRC Entry Guide</h3><div className={styles.guide}><p><b>SA105 – Box 20</b><span>Total rents and other income from property</span><strong>{money(rent)}</strong><small>Calculated from this person’s share of {properties.length} property record(s).</small></p><p><b>SA105 – Box 24</b><span>Rent, rates, insurance and ground rents</span><strong>{money(rentCosts)}</strong></p><p><b>SA105 – Boxes 25–29</b><span>Other allowable property expense categories</span><strong>{money(exp-rentCosts)}</strong></p><p><b>SA100 – Interest</b><span>UK bank/building society interest</span><strong>{money(interest)}</strong></p><p><b>SA100 – Pensions</b><span>Private pension income recorded</span><strong>{money(pension)}</strong></p></div></article>})}</section> }
function EntryForm({kind,properties,p1Name,p2Name,onSave,onCancel}:{kind:Entry["kind"];properties:Property[];p1Name:string;p2Name:string;onSave:(e:FormEvent<HTMLFormElement>)=>void;onCancel:()=>void}) { const expense=kind==="Expense"; return <div className={styles.overlay}><form className={styles.modal} onSubmit={onSave}><div className={styles.modalHead}><h2>Add {kind === "Rent" ? "rental income" : kind.toLowerCase()}</h2><button type="button" onClick={onCancel}>×</button></div><label>Date<input name="date" type="date" required defaultValue="2025-05-01"/></label><label>Description<input name="description" required placeholder="For example, May rent"/></label><label>Amount (£)<input name="amount" type="number" step="0.01" min="0" required/></label>{(kind==="Rent"||expense)&&<label>Property<select name="property" required><option value="">Choose property</option>{properties.map(p=><option key={p.id}>{p.name}</option>)}</select></label>}<label>Ownership<select name="ownership" defaultValue="Joint"><option value="Person 1">{p1Name}</option><option value="Person 2">{p2Name}</option><option>Joint</option></select></label>{expense&&<label>Expense category<select name="category" required><option>Rent, rates, insurance and ground rent</option><option>Repairs and maintenance</option><option>Legal fees</option><option>Management/accountancy/professional fees</option><option>Services provided</option><option>Cleaning</option><option>Gardening</option><option>Utilities paid by landlord</option><option>Replacement domestic items</option><option>Other allowable property expenses</option><option>Finance costs, where relevant</option><option>Other / needs review</option></select></label>}<label>Receipt / document (camera, photos or files)<input name="receipt" type="file" accept="image/*,application/pdf"/></label><label className={styles.checkbox}><input name="review" type="checkbox"/> Needs tax treatment checking</label><div className={styles.formButtons}><button type="button" onClick={onCancel}>Cancel</button><button className={styles.primary}>Save record</button></div></form></div> }
function PropertyForm({p1Name,p2Name,initial,onSave,onCancel}:{p1Name:string;p2Name:string;initial:Property|null;onSave:(e:FormEvent<HTMLFormElement>)=>void;onCancel:()=>void}) { return <div className={styles.overlay}><form className={styles.modal} onSubmit={onSave}><div className={styles.modalHead}><h2>{initial ? "Edit property" : "Add property"}</h2><button type="button" onClick={onCancel}>×</button></div><label>Property name/reference<input name="name" required placeholder="For example, Flat 1" defaultValue={initial?.name}/></label><label>Address<textarea name="address" required defaultValue={initial?.address}/></label><label>Ownership<select name="ownership" defaultValue={initial?.ownership ?? "Joint"}><option value="Person 1">{p1Name}</option><option value="Person 2">{p2Name}</option><option>Joint</option></select></label><div className={styles.twocol}><label>{p1Name} %<input name="p1" type="number" defaultValue={initial?.p1 ?? 50} min="0" max="100" required/></label><label>{p2Name} %<input name="p2" type="number" defaultValue={initial?.p2 ?? 50} min="0" max="100" required/></label></div><label className={styles.checkbox}><input name="active" type="checkbox" defaultChecked={initial?.active ?? true}/> Active property</label><div className={styles.formButtons}><button type="button" onClick={onCancel}>Cancel</button><button className={styles.primary}>{initial ? "Save changes" : "Save property"}</button></div></form></div> }

export default function Home() { return <AuthGate><TaxApp /></AuthGate>; }
