-- Bradley Tax Records: private household data model. Run this migration in the linked Supabase project.
create extension if not exists pgcrypto;
insert into storage.buckets (id, name, public) values ('tax-documents', 'tax-documents', false)
on conflict (id) do update set public = false;
create table public.households (id uuid primary key default gen_random_uuid(), name text not null default 'Bradley Tax Records', created_at timestamptz not null default now());
create table public.household_members (household_id uuid not null references public.households(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null check(role in ('owner','member')), primary key(household_id,user_id));
create table public.taxpayers (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, label text not null, display_name text not null, sort_order smallint not null, unique(household_id,label));
create table public.tax_years (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, label text not null, starts_on date not null, ends_on date not null, unique(household_id,starts_on), check(ends_on > starts_on));
create table public.properties (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, name text not null, address text, ownership text not null check(ownership in ('person_1','person_2','joint')), person_1_pct numeric(5,2) not null default 50 check(person_1_pct between 0 and 100), person_2_pct numeric(5,2) not null default 50 check(person_2_pct between 0 and 100), first_let_on date, ceased_on date, notes text, active boolean not null default true, check(person_1_pct + person_2_pct = 100));
create table public.transactions (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, tax_year_id uuid not null references public.tax_years(id), property_id uuid references public.properties(id), taxpayer_id uuid references public.taxpayers(id), kind text not null check(kind in ('rental_income','property_expense','state_pension','private_pension','bank_interest','other_income')), occurred_on date not null, description text, supplier_or_provider text, gross_amount numeric(12,2) not null check(gross_amount >= 0), tax_deducted numeric(12,2) default 0, ownership text not null check(ownership in ('person_1','person_2','joint')), person_1_pct numeric(5,2) not null default 50 check(person_1_pct between 0 and 100), person_2_pct numeric(5,2) not null default 50 check(person_2_pct between 0 and 100), expense_category text, needs_review boolean not null default false, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(person_1_pct + person_2_pct = 100));
create table public.documents (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, transaction_id uuid references public.transactions(id) on delete cascade, property_id uuid references public.properties(id) on delete set null, tax_year_id uuid references public.tax_years(id), storage_path text not null unique, original_name text not null, mime_type text, document_type text not null, created_at timestamptz not null default now());
create table public.hmrc_mappings (id uuid primary key default gen_random_uuid(), tax_year_id uuid not null references public.tax_years(id) on delete cascade, transaction_kind text not null, expense_category text, form_name text not null, box_reference text, field_description text not null, unique(tax_year_id,transaction_kind,expense_category));
create table public.audit_log (id bigint generated always as identity primary key, household_id uuid not null references public.households(id) on delete cascade, actor_id uuid references auth.users(id), table_name text not null, record_id uuid, action text not null, before_data jsonb, after_data jsonb, occurred_at timestamptz not null default now());
alter table public.households enable row level security; alter table public.household_members enable row level security; alter table public.taxpayers enable row level security; alter table public.tax_years enable row level security; alter table public.properties enable row level security; alter table public.transactions enable row level security; alter table public.documents enable row level security; alter table public.hmrc_mappings enable row level security; alter table public.audit_log enable row level security;
create function public.is_household_member(target_household uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.household_members where household_id=target_household and user_id=(select auth.uid())) $$;
revoke all on function public.is_household_member(uuid) from public; grant execute on function public.is_household_member(uuid) to authenticated;
create policy "members manage households" on public.households for all to authenticated using (public.is_household_member(id)) with check (public.is_household_member(id));
create policy "members see own membership" on public.household_members for select to authenticated using (user_id=(select auth.uid()));
create policy "owners manage membership" on public.household_members for all to authenticated using (exists(select 1 from public.household_members m where m.household_id=household_id and m.user_id=(select auth.uid()) and m.role='owner')) with check (exists(select 1 from public.household_members m where m.household_id=household_id and m.user_id=(select auth.uid()) and m.role='owner'));
create policy "household taxpayer access" on public.taxpayers for all to authenticated using (public.is_household_member(household_id)) with check (public.is_household_member(household_id));
create policy "household tax year access" on public.tax_years for all to authenticated using (public.is_household_member(household_id)) with check (public.is_household_member(household_id));
create policy "household property access" on public.properties for all to authenticated using (public.is_household_member(household_id)) with check (public.is_household_member(household_id));
create policy "household transaction access" on public.transactions for all to authenticated using (public.is_household_member(household_id)) with check (public.is_household_member(household_id));
create policy "household document access" on public.documents for all to authenticated using (public.is_household_member(household_id)) with check (public.is_household_member(household_id));
create policy "mapping access through tax year" on public.hmrc_mappings for all to authenticated using (exists(select 1 from public.tax_years y where y.id=tax_year_id and public.is_household_member(y.household_id))) with check (exists(select 1 from public.tax_years y where y.id=tax_year_id and public.is_household_member(y.household_id)));
create policy "household audit access" on public.audit_log for select to authenticated using (public.is_household_member(household_id));
-- Original files are private and may only be reached by members of the owning household.
create policy "household files are private" on storage.objects for all to authenticated using (bucket_id='tax-documents' and public.is_household_member(((storage.foldername(name))[1])::uuid)) with check (bucket_id='tax-documents' and public.is_household_member(((storage.foldername(name))[1])::uuid));
